language: node_js
node_js:
  - 12
  - 14
  - 16

matrix:
  include:
    - os: osx

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test

cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm
    - node_modules # npm install, unlike npm ci, doesn't wipe node_modules
