language: node_js

sudo: false

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
dist: xenial
services:
  - xvfb

os:
  - osx
  - linux
  - windows

node_js:
  - '8'
  - '10'

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test
