language: node_js

sudo: false

# NOTE: https://docs.travis-ci.com/user/multi-os/, could maybe used here.
# https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
dist: xenial
services:
  - xvfb

os:
  - osx
  - linux
  # - windows # does not work currently, temporary disabled

node_js:
  - '10'
  - '12'

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test

cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm
    - node_modules # npm install, unlike npm ci, doesn't wipe node_modules
